version: '3.8'

services:
  # Database MySQL
  mysql:
    image: mysql:8.0
    container_name: umroh_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: umroh_management
      MYSQL_USER: umroh_user
      MYSQL_PASSWORD: umroh_password_2024
      MYSQL_ROOT_PASSWORD: root_password_2024
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/comprehensive-schema.sql:/docker-entrypoint-initdb.d/02-comprehensive-schema.sql
      - ./database/triggers-procedures.sql:/docker-entrypoint-initdb.d/03-triggers-procedures.sql
      - ./backend/migrations:/docker-entrypoint-initdb.d/migrations
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=256M
      --max_connections=200
    networks:
      - umroh_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
      interval: 30s

  # Redis untuk caching dan session
  redis:
    image: redis:7-alpine
    container_name: umroh_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - umroh_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      retries: 5
      interval: 30s

  # Main Application
  umroh_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: umroh_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      # Database
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: umroh_management
      DB_USER: umroh_user
      DB_PASSWORD: umroh_password_2024
      
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      
      # JWT
      JWT_SECRET: your_super_secret_jwt_key_change_this_in_production
      JWT_EXPIRES_IN: 7d
      
      # App Config
      NODE_ENV: production
      PORT: 5000
      
      # File Upload
      MAX_FILE_SIZE: 10485760
      UPLOAD_PATH: ./uploads
      
      # Email (opsional)
      EMAIL_SERVICE: gmail
      EMAIL_USER: your-email@gmail.com
      EMAIL_PASSWORD: your-app-password
      
      # Backup
      BACKUP_PATH: ./backups
      
      # Security
      RATE_LIMIT_WINDOW: 900000
      RATE_LIMIT_MAX: 100
      
      # Performance
      CACHE_TTL: 3600
      
    volumes:
      - app_uploads:/app/uploads
      - app_logs:/app/logs
      - app_backups:/app/backups
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - umroh_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      timeout: 10s
      retries: 3
      interval: 30s

  # Nginx Reverse Proxy (opsional untuk production)
  nginx:
    image: nginx:alpine
    container_name: umroh_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - app_uploads:/app/uploads:ro
    depends_on:
      - umroh_app
    networks:
      - umroh_network

volumes:
  mysql_data:
  redis_data:
  app_uploads:
  app_logs:
  app_backups:

networks:
  umroh_network:
    driver: bridge
